-- Your SQL goes here
CREATE TABLE team_shares (
  id bigint primary key GENERATED BY DEFAULT AS IDENTITY,
  team_id bigint NOT NULL,
  shared_entity INTEGER NOT NULL,
  shared_id bigint NOT NULL,
  inserted_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE unique index team_shares_unique_idx on team_shares (team_id, shared_entity, shared_id);

