use common::models::app_column::TypeValidation;
use leptos::{component, view, IntoView, ReadSignal, SignalGet, WriteSignal};
use web_sys::{console, wasm_bindgen::JsValue};

#[component]
pub fn TypeValidationFormLastModifiedBy(
    tv: ReadSignal<Option<TypeValidation>>,
    set_tv: WriteSignal<Option<TypeValidation>>,
    set_error: WriteSignal<bool>,
) -> impl IntoView {
    view! {
        <div class="note">
            Automatically generated by the system, indicating the user who last updated the record.
        </div>
    }
}
