-- Your SQL goes here
CREATE TABLE apps (
  id int primary key GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255) NOT NULL,
  schema_name VARCHAR(255) NOT NULL,
  color VARCHAR(255) not NULL,
  description TEXT,
  inserted_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE unique index apps_schema_name on apps (schema_name);
CREATE unique index apps_name on apps (name);
DROP TABLE IF EXISTS applications;
