[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.1.0", features = ["postgres", "serde_json", "chrono"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4.9", features = ["serde"] }
crud_derive = { path = "../backend/crud_derive" }
num-format = "0.4.4"
