// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use std::io::Write;

use super::schema::*;
use bigdecimal::BigDecimal;
use chrono::{DateTime, NaiveDate, NaiveDateTime};
use diesel::deserialize::{self, FromSql, FromSqlRow};
use diesel::expression::AsExpression;
use diesel::pg::PgValue;
use diesel::prelude::*;
use diesel::serialize::{self, IsNull, Output, ToSql};
use diesel::sql_types::SqlType;
use diesel::{
    pg::Pg,
    sql_types::{Array, Float8, Int4},
    PgConnection,
};
use serde_json;

use diesel::result::Error;
use serde::{Deserialize, Serialize};

use crud_derive::{Changeset, DatabaseEnum, View};

use chrono::Utc;

use diesel::debug_query;

use diesel::sql_types::HasSqlType;

// pub trait Crud<T> {
//     fn create(conn: &mut PgConnection, model: &T) -> Result<T, Error>;
//     fn read(conn: &mut PgConnection, id: i32) -> Result<T, Error>;
//     fn update(conn: &mut PgConnection, id: i32, updated_model: &T) -> Result<T, Error>;
//     fn delete(conn: &mut PgConnection, id: i32) -> Result<(), Error>;
// }
//
//

#[derive(Debug)]
pub struct CustomEnumError {
    msg: String,
    status: u16,
}

impl CustomEnumError {
    fn not_found(msg: String) -> Self {
        Self { msg, status: 404 }
    }
}

use uuid::Uuid;
#[derive(Queryable, Debug)]
pub struct AlertEvent {
    pub id: i64,
    pub alert_setting_id: i64,
    pub alert_level: i32,
    pub original_data: Option<serde_json::Value>,
    pub transformed_data_column_name: Option<String>,
    pub is_data_saved: bool,
    pub inserted_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct AlertEventsTransformedData {
    pub id: i64,
    pub value: Option<String>,
    pub level: i32,
    pub alert_event_id: i64,
    pub inserted_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct AlertLevelSetting {
    pub id: i64,
    pub level: i32,
    pub value: String,
    pub alert_setting_id: i64,
    pub inserted_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct AlertNotificationSetting {
    pub id: i64,
    pub method: i32,
    pub recipients: Vec<Option<String>>,
    pub alert_setting_id: i64,
    pub inserted_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct AlertSetting {
    pub id: i64,
    pub name: String,
    pub question_id: i64,
    pub column: String,
    pub aggregation: i32,
    pub number_of_rows: i32,
    pub operation: i32,
    pub traversal: i32,
    pub is_active: bool,
    pub frequency_value_in_seconds: i32,
    pub start_time: NaiveDateTime,
    pub scheduled_disabled_config: Option<serde_json::Value>,
    pub silent_till: Option<NaiveDateTime>,
    pub next_run_time: Option<NaiveDateTime>,
    pub status: Option<i32>,
    pub inserted_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct Alert {
    pub id: i32,
    pub name: Option<String>,
    pub config: Option<serde_json::Value>,
    pub question_id: Option<i32>,
    pub inserted_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct ApiActionLog {
    pub id: i32,
    pub api_action_id: Option<i32>,
    pub url: String,
    pub request_headers: Option<serde_json::Value>,
    pub response_headers: Option<serde_json::Value>,
    pub request_body: Option<String>,
    pub response_body: Option<String>,
    pub request_method: Option<i32>,
    pub status_code: Option<i32>,
    pub variables: Option<Vec<Option<String>>>,
    pub user_id: Option<i32>,
    pub inserted_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(
    Debug, PartialEq, FromSqlRow, AsExpression, Eq, Serialize, Deserialize, Clone, DatabaseEnum,
)]
#[diesel(sql_type = Int4)]
#[serde(rename_all = "snake_case")]
pub enum ActionLevel {
    QuestionResponse = 1,
    Question = 2,
}

#[derive(
    Debug,
    PartialEq,
    FromSqlRow,
    AsExpression,
    Eq,
    Serialize,
    Deserialize,
    Clone,
    DatabaseEnum,
    Default,
)]
#[diesel(sql_type = Int4)]
pub enum HTTPMethod {
    #[default]
    GET = 1,
    POST = 2,
    PUT = 3,
    DELETE = 4,
    PATCH = 5,
}

#[derive(Queryable, Debug, Changeset, View, Serialize, Deserialize, Default)]
#[view_skip_fields = "on_success, on_failure, failure_message, failure_key, success_message, success_key, action_level"]
pub struct ApiAction {
    #[skip_in_changeset]
    pub id: i32,
    pub question_id: Option<i32>,
    pub url: String,
    pub headers: Option<serde_json::Value>,
    pub body: Option<String>,
    pub method: Option<HTTPMethod>,
    pub name: Option<String>,
    pub color: Option<String>,
    pub open_in_new_tab: Option<bool>,
    pub response_settings: Option<serde_json::Value>,
    pub hidden: Option<bool>,
    #[serde(skip_deserializing)]
    pub inserted_at: NaiveDateTime,
    #[serde(skip_deserializing)]
    pub updated_at: NaiveDateTime,
    pub column: Option<String>,
    pub on_success: Option<i32>,
    pub on_failure: Option<i32>,
    pub failure_message: Option<String>,
    pub failure_key: Option<String>,
    pub success_message: Option<String>,
    pub success_key: Option<String>,
    pub action_level: Option<ActionLevel>,
    pub visualization_id: Option<i32>,
    pub loading_message: Option<String>,
    pub display_settings: Option<serde_json::Value>,
    pub open_option: Option<String>,
}

#[derive(Queryable, Debug)]
pub struct Application {
    pub id: i64,
    pub name: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct AuditLog {
    pub id: i64,
    pub whodunit: Option<i32>,
    pub action: Option<i32>,
    pub additional_data: Option<serde_json::Value>,
    pub inserted_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct ColumnValue {
    pub id: i32,
    pub name: Option<String>,
    pub value: Option<String>,
    pub column_id: Option<i32>,
    pub inserted_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug, Serialize, Deserialize, Changeset, View)]
#[table_name = "columns_"]
pub struct Column {
    #[skip_in_changeset]
    pub id: i32,
    pub name: Option<String>,
    pub table_id: Option<i32>,
    #[serde(skip_deserializing)]
    pub inserted_at: NaiveDateTime,
    #[serde(skip_deserializing)]
    pub updated_at: NaiveDateTime,
    pub data_type: Option<String>,
    pub description: Option<String>,
    pub primary_key: Option<bool>,
}

#[derive(Queryable, Debug)]
pub struct DashboardWidget {
    pub id: i64,
    pub widget_type: Option<String>,
    pub widget_id: Option<i64>,
    pub dashboard_id: Option<i64>,
    pub inserted_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug, Serialize, Deserialize, Changeset, View)]
#[view_skip_fields = "shareable_link, is_shareable_link_public, settings"]
pub struct Dashboard {
    #[skip_in_changeset]
    pub id: i32,
    pub title: Option<String>,
    pub update_interval: Option<i32>,
    pub last_updated: Option<NaiveDateTime>,
    #[serde(skip_deserializing)]
    pub inserted_at: NaiveDateTime,
    #[serde(skip_deserializing)]
    pub updated_at: NaiveDateTime,
    pub description: Option<String>,
    pub shareable_link: Option<Uuid>,
    pub is_shareable_link_public: Option<bool>,
    pub settings: Option<serde_json::Value>,
    pub shared_to: Option<Vec<Option<String>>>,
    pub owner_id: Option<i32>,
    pub notes_settings: Option<serde_json::Value>,
}

#[derive(Queryable, Debug, Insertable, AsChangeset, Serialize, Deserialize, Changeset)]
pub struct Database {
    #[skip_in_changeset]
    pub id: i32,
    pub name: Option<String>,
    pub db_type: Option<String>,
    pub config: Option<serde_json::Value>,
    #[serde(skip_deserializing)]
    pub inserted_at: NaiveDateTime,
    #[serde(skip_deserializing)]
    pub updated_at: NaiveDateTime,
    #[serde(skip_deserializing)]
    pub last_accessed_at: Option<NaiveDateTime>,
    pub unique_identifier: Option<Uuid>,
}

#[derive(Queryable, Debug)]
pub struct ForeignKey {
    pub id: i32,
    pub name: Option<String>,
    pub fk_type: Option<i32>,
    pub column_id: Option<i32>,
    pub foreign_column_id: Option<i32>,
    pub inserted_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct GeneratedAlert {
    pub id: i32,
    pub alert_id: Option<i32>,
    pub status: Option<i32>,
    pub failing_conditions: Option<Vec<Option<serde_json::Value>>>,
    pub inserted_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug, Serialize, Deserialize, Changeset, View)]
pub struct Note {
    #[skip_in_changeset]
    pub id: i32,
    pub content: String,
    pub dashboard_id: Option<i32>,
    #[serde(skip_deserializing)]
    pub inserted_at: NaiveDateTime,
    #[serde(skip_deserializing)]
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug, Serialize, Deserialize, Changeset, View)]
#[id_data_type = "i64"]
pub struct OrganizationSetting {
    #[skip_in_changeset]
    pub id: i64,
    pub name: String,
    pub value: Option<String>,
    pub setting_type: i32,
    pub organization_id: i64,
    pub api_action_id: Option<i64>,
    #[serde(skip_deserializing)]
    pub inserted_at: NaiveDateTime,
    #[serde(skip_deserializing)]
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug, Serialize, Deserialize, Changeset, View)]
#[id_data_type = "i64"]
pub struct Organization {
    #[skip_in_changeset]
    pub id: i64,
    pub name: String,
    pub google_domain: String,
    pub is_deactivated: bool,
    #[serde(skip_deserializing)]
    pub inserted_at: NaiveDateTime,
    #[serde(skip_deserializing)]
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug, Serialize, Deserialize, Changeset, View)]
pub struct PermissionSet {
    pub id: i32,
    pub name: Option<String>,
    #[serde(skip_deserializing)]
    pub inserted_at: NaiveDateTime,
    #[serde(skip_deserializing)]
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug, Insertable, AsChangeset, Serialize, Deserialize)]
pub struct Permission {
    pub id: i32,
    pub permission_set_id: Option<i32>,
    pub name: Option<String>,
    pub inserted_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct QuestionBank {
    pub id: i32,
    pub title: Option<String>,
    pub questions: Option<Vec<Option<i32>>>,
    pub inserted_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct QuestionWidget {
    pub id: i32,
    pub widget_id: Option<i32>,
    pub question_id: Option<i32>,
}

#[derive(
    Debug, PartialEq, FromSqlRow, AsExpression, Eq, Serialize, Deserialize, Clone, DatabaseEnum,
)]
#[diesel(sql_type = Int4)]
#[serde(rename_all = "snake_case")]
pub enum QueryType {
    HumanSql = 0,
    Sql = 1,
    ApiClient = 2,
}

#[derive(Queryable, Debug, Serialize, Deserialize, Changeset, View)]
// #[view_skip_fields = "results_view_settings, cached_results, columns"]
pub struct Question {
    pub id: i32,
    pub title: Option<String>,
    pub last_updated: Option<NaiveDateTime>,
    pub sql: Option<String>,
    pub human_sql: Option<serde_json::Value>,
    #[serde(skip_deserializing)]
    pub inserted_at: NaiveDateTime,
    #[serde(skip_deserializing)]
    pub updated_at: NaiveDateTime,
    pub query_type: Option<QueryType>,
    pub shareable_link: Option<Uuid>,
    pub is_shareable_link_public: Option<bool>,
    pub results_view_settings: Option<serde_json::Value>,
    pub columns_: Option<Vec<Option<String>>>,
    pub cached_results: Option<serde_json::Value>,
    pub shared_to: Option<Vec<Option<String>>>,
    pub owner_id: Option<i32>,
    pub config: Option<serde_json::Value>,
}

#[derive(Queryable, Debug)]
pub struct ResultsCache {
    pub id: i64,
    pub key: Option<String>,
    pub sql: Option<String>,
    pub data: Option<serde_json::Value>,
    pub expiry_time: Option<NaiveDateTime>,
    pub inserted_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct RulesEnginePermission {
    pub id: i64,
    pub role_id: i64,
    pub name: i32,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct RulesEngineRole {
    pub id: i64,
    pub name: String,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct RulesEngineUser {
    pub id: i64,
    pub name: Option<String>,
    pub email: String,
    pub is_deactivated: bool,
    pub profile_pic: Option<String>,
    pub metadata: Option<serde_json::Value>,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct Schedule {
    pub id: i64,
    pub every: Option<i32>,
    pub time_unit: Option<String>,
    pub time_details: Option<Vec<Option<serde_json::Value>>>,
    pub next_execution_time: Option<NaiveDateTime>,
    pub is_running: Option<bool>,
    pub job_details: Option<serde_json::Value>,
    pub is_active: Option<bool>,
    pub recipients: Option<Vec<Option<String>>>,
    pub timezone: Option<String>,
    pub inserted_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct SearchableColumn {
    pub id: i64,
    pub name: Option<String>,
    pub snapshot_id: Option<i32>,
    pub value: Option<String>,
    pub inserted_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub snapshot_data_identifier: Option<Uuid>,
}

#[derive(Queryable, Debug)]
pub struct SendAlertConfig {
    pub id: i32,
    pub alert_id: Option<i32>,
    pub message_template: Option<String>,
    pub comm_type: Option<i32>,
    pub to_addresses: Option<Vec<Option<String>>>,
    pub subject_template: Option<String>,
    pub inserted_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug, Serialize, Deserialize, Changeset, View)]
pub struct Setting {
    #[skip_in_changeset]
    pub id: i32,
    pub name: String,
    pub value: Option<String>,
    #[serde(skip_deserializing)]
    pub inserted_at: NaiveDateTime,
    #[serde(skip_deserializing)]
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct SheetConfig {
    pub id: i64,
    pub name: Option<String>,
    pub table_name: Option<String>,
    pub refresh_interval: Option<i32>,
    pub sheet_id: Option<String>,
    pub subsheet_id: Option<i32>,
    pub api_key_id: Option<i64>,
    pub inserted_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct SnapshotData {
    pub id: i64,
    pub row: serde_json::Value,
    pub snapshot_id: Option<i32>,
    pub inserted_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub identifier: Option<Uuid>,
}

#[derive(Queryable, Debug)]
pub struct Snapshot {
    pub id: i64,
    pub name: String,
    pub description: Option<String>,
    pub columns_: Option<Vec<Option<String>>>,
    pub question_id: i32,
    pub inserted_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub scheduled: Option<bool>,
    pub interval: Option<i32>,
    pub starting_at: Option<NaiveDateTime>,
    pub status: Option<i32>,
    pub should_save_data_to_db: Option<bool>,
    pub should_create_csv: Option<bool>,
    pub should_send_mail_on_completion: Option<bool>,
    pub mail_to: Option<Vec<Option<String>>>,
    pub parent_id: Option<i32>,
    pub searchable_columns: Option<Vec<Option<String>>>,
    pub keep_latest: Option<i32>,
}

#[derive(Queryable, Debug)]
pub struct Snippet {
    pub id: i64,
    pub name: Option<String>,
    pub text: Option<String>,
    pub database_id: Option<i64>,
    pub owner_id: Option<i64>,
    pub expand_on_select: Option<bool>,
    pub inserted_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug, Serialize, Deserialize, Changeset, View)]
pub struct Table {
    #[skip_in_changeset]
    pub id: i32,
    pub name: Option<String>,
    pub database_id: Option<i32>,
    #[serde(skip_deserializing)]
    pub inserted_at: NaiveDateTime,
    #[serde(skip_deserializing)]
    pub updated_at: NaiveDateTime,
    pub readable_table_name: Option<String>,
    pub description: Option<String>,
}

#[derive(Queryable, Debug)]
pub struct TagDashboard {
    pub id: i32,
    pub tag_id: Option<i32>,
    pub dashboard_id: Option<i32>,
    pub inserted_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct TagQuestion {
    pub id: i32,
    pub tag_id: Option<i32>,
    pub question_id: Option<i32>,
    pub inserted_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug, Serialize, Deserialize, Changeset, View)]
pub struct Tag {
    #[skip_in_changeset]
    pub id: i32,
    pub name: String,
    pub description: Option<String>,
    #[serde(skip_deserializing)]
    pub inserted_at: NaiveDateTime,
    #[serde(skip_deserializing)]
    pub updated_at: NaiveDateTime,
    pub color: Option<String>,
}

#[derive(Queryable, Debug, Changeset, View, Serialize, Deserialize)]
pub struct TeamDatabase {
    #[skip_in_changeset]
    pub id: i32,
    pub database_id: Option<i32>,
    pub team_id: Option<i32>,
    pub inserted_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug, Serialize, Deserialize, View, Changeset)]
#[view_skip_fields("field_to_skip")]
pub struct Team {
    #[skip_in_changeset]
    pub id: i32,
    pub name: String,
    pub description: Option<String>,
    #[serde(skip_deserializing)]
    pub inserted_at: NaiveDateTime,
    #[serde(skip_deserializing)]
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug, Serialize, Deserialize, Changeset, View)]
pub struct UserPermissionSet {
    #[skip_in_changeset]
    pub id: i32,
    pub user_id: Option<i32>,
    pub permission_set_id: Option<i32>,
    pub inserted_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

// #[derive(SqlType)]
// #[diesel(postgres_type(name = "My_Type"))]
// pub struct MyType;

#[derive(
    Debug, PartialEq, FromSqlRow, AsExpression, Eq, Serialize, Deserialize, Clone, DatabaseEnum,
)]
#[diesel(sql_type = Int4)]
#[serde(rename_all = "lowercase")]
pub enum SettingsTypes {
    General = 1,
    Variable = 2,
}

#[derive(Queryable, Debug, Serialize, Deserialize, Changeset, View)]
#[id_data_type = "i64"]
pub struct UserSetting {
    pub id: i64,
    pub name: String,
    pub value: Option<String>,
    pub setting_type: SettingsTypes,
    pub user_id: i64,
    pub api_action_id: Option<i64>,
    #[serde(skip_deserializing)]
    pub inserted_at: NaiveDateTime,
    #[serde(skip_deserializing)]
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug, Changeset, Serialize, Deserialize)]
pub struct UserTeam {
    #[skip_in_changeset]
    pub id: i32,
    pub user_id: Option<i32>,
    pub team_id: Option<i32>,
    #[serde(skip_deserializing)]
    pub inserted_at: NaiveDateTime,
    #[serde(skip_deserializing)]
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug, Serialize, Deserialize, Changeset, View)]
pub struct User {
    #[skip_in_changeset]
    pub id: i32,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub email: Option<String>,
    pub full_name: Option<String>,
    pub profile_pic: Option<String>,
    pub metadata: Option<serde_json::Value>,
    #[serde(skip_deserializing)]
    pub inserted_at: NaiveDateTime,
    #[serde(skip_deserializing)]
    pub updated_at: NaiveDateTime,
    pub is_deactivated: Option<bool>,
    pub organization_id: Option<i64>,
    pub password: Option<String>,
}

#[derive(Queryable, Debug, Serialize, Deserialize, Changeset, View)]
#[view_skip_fields = "default_operator, default_options, question_filter_id, column_id"]
pub struct Variable {
    #[skip_in_changeset]
    pub id: i32,
    pub name: Option<String>,
    pub default: Option<String>,
    pub var_type: Option<String>,
    pub column_id: Option<i32>,
    pub question_id: Option<i32>,
    pub dashboard_id: Option<i32>,
    pub default_operator: Option<String>,
    #[serde(skip_deserializing)]
    pub inserted_at: NaiveDateTime,
    #[serde(skip_deserializing)]
    pub updated_at: NaiveDateTime,
    pub question_filter_id: Option<i32>,
    pub default_options: Option<Vec<Option<serde_json::Value>>>,
}

#[derive(Queryable, Debug, Serialize, Deserialize, Changeset, View)]
#[id_data_type = "i64"]
pub struct Visualization {
    #[skip_in_changeset]
    pub id: i64,
    pub name: Option<String>,
    pub settings: Option<serde_json::Value>,
    pub query_terms: Option<serde_json::Value>,
    pub renderer_type: Option<String>,
    pub question_id: Option<i64>,
    #[serde(skip_deserializing)]
    pub inserted_at: NaiveDateTime,
    #[serde(skip_deserializing)]
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct WidgetItem {
    pub id: i32,
    pub text: Option<String>,
    pub config: Option<serde_json::Value>,
    pub value: Option<String>,
    pub widget_id: Option<i32>,
    pub inserted_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct Widget {
    pub id: i32,
    pub column_name: String,
    pub name: String,
    pub renderer: Option<i32>,
    pub inserted_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug, Serialize, Deserialize, Changeset, View, QueryableByName)]
#[table_name = "bg_queue"]
#[id_data_type = "Uuid"]
pub struct BgJob {
    pub id: Uuid,
    pub inserted_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub scheduled_for: NaiveDateTime,
    pub failed_attempts: i32,
    pub status: JobStatus,
    pub message: serde_json::value::Value,
}

#[derive(
    Debug, PartialEq, FromSqlRow, AsExpression, Eq, Serialize, Deserialize, Clone, DatabaseEnum,
)]
#[diesel(sql_type = Int4)]
#[serde(rename_all = "snake_case")]
pub enum JobStatus {
    Queued = 1,
    Running = 2,
    Failed = 3,
}
