-- Your SQL goes here
CREATE TABLE system_variables (
  id bigint primary key GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255) NOT NULL,
  value bytea NOT NULL,
  additional_data bytea NOT NULL,
  inserted_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE unique index system_variable_unique_name on system_variables (name);
