-- Your SQL goes here
CREATE TABLE app_tables (
  id bigint primary key GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255) NOT NULL,
  real_name VARCHAR(63) NOT NULL,
  description TEXT,
  app_id int NOT NULL,
  inserted_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE unique index app_tables_name_app_id on app_tables (app_id, real_name);

CREATE TABLE app_columns (
  id bigint primary key GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255) NOT NULL,
  real_name VARCHAR(63) NOT NULL,
  description TEXT,
  table_id bigint NOT NULL,
  type_validation jsonb NOT NULL,
  display_order integer NOT NULL,
  inserted_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE unique index app_columns_name_table_id on app_columns (table_id, real_name);
